### ISSUE TITLE
Odd distance

### ISSUE THREAD

**Issue by poet-man** [y20k/trackbook#21]
Despite I am German, I try in English, so everybody can read:
Sometimes (maybe 1 out of 5) records display a distance, that cannot be true (s.attached screenshot). So far, I thought, maybe decimal point is just missing (so having 250000 meters instead of 2500,00). But today I donot think, distance is right at all (but maybe I am wrong).
Anyway .... attachement shows wrong result. All the other numbers on that screenshot should be correct. All the others .... but "Schrittzähler" (how could I have this correct too).
Most times (4 out of 5, or so)distance is correct.
Thanks.
![screenshot_20170701-120407](https://user-images.githubusercontent.com/22373747/27761194-a15174fe-5e57-11e7-9564-70434cbedee8.png)

**Comment by y20k** [comment]
Thanks for the bug report. 

I have had the same experience, too. Sometimes Trackbook records a location that does not make sense. There should be a blue dot somewhere FAR away from your main track.

The problem occurs when you are somewhere, where there is no GPS for a while. Then Trackbook falls back to Cell tower triangulation. Being off by 200+ km is a rarety. I had that once when I took the train.

I think this bug may be a duplicate. #4 describes a similar problem. I need to come up with an algorithm that on the one hand factors in the possiblity that a user switches a transportation method - eg. from bicycle to airplane... and that on the other hand does not record unrealistic waypoints.

I will try to find a solution.

Did anything unusual occur during your recording? Did you stop somewhere, did you change transportation?

And about the step counter (Schrittzähler)... Does you device have a step counter built in?

**Comment by y20k** [comment]
Trackbook fetches the last known location from the OS upon start. It takes few seconds to get a more current location fix. If started directly after opening the app it takes the last known location as the start of the recording, which is often pretty accurate. In your scenario it is understandably very incorrect.

I think a timestamp check of the last known location would mitigate your problem. I will look into this. Thanks for the detailed report!

**Comment by Hob111** [comment]
What you say sounds very plausible, I think I need to be more patient and give Trackbook more time before I start tracking. Your reasoning also explains poet-man's problems, in areas where the GPS signal is poor it will take longer to fix the current location.

There are 2 things that still puzzle me.
 
1) The *incorrect* point at the start of the track is used in the distance calculation but is not displayed as the start time or used in the duration of the walk? Poet-man made similar observations. I assume you determine start time independently of the data in the GPX file?
2) Why is the odd point at the beginning plotted in grey not blue? I don't think my eyes deceive me. I'm happy to upload the whole GPX file if it helps.

**Comment by Hob111** [comment]
This has happened to me again on a recent walk. The usual problem, I started Trackbook in a rush at the start of the walk and it used the last known location as the start of the walk. It seems to me the problem is that Trackbook gives no indication of when it receives a current location and the map isn't refreshed until tracking has started. Would it be difficult to get Trackbook to update the map as soon as a current location was obtained?

**Comment by y20k** [comment]
I know I know. I experience this behaviour from time to time, too. I still intend to fix the bug, where the first location is way off. I just did not find the time. A lot of stuff to do at work. Not much free time to spare. 

I added the tag "help wanted". So if anyone who likes to help us out here read this, don't hesitate. 

Anyway. As soon as I find a few hours I will try to fix it. For now the bug is still "open" and un-assigned.

**Comment by Hob111** [comment]
Sorry, I didn't intend to hassle.

I was merely wondering if it would be simpler (programming wise) to give the user a visual sign that the location was current rather than checking the timestamp. If no map was displayed until the current location had been acquired the user would know it was OK to start tracking. I can't read the code (see below) so I don't know if you store the location and map between sessions and if this could be changed.

I'd love to help. sadly my programming ended with Fortran, my scripting with Perl and my O/S with Linux. 😞

**Comment by y20k** [comment]
@Hob111 & @poet-man 

I made a little change to the app. Trackbook now should only add a location to a recording, if it is accurate enough and current enough.

**Accurate enough** is for now defined as: probably within a **50m radius** (at the time of recording). And **current enough** would be within the **last two minutes**.

I wonder especially if two minutes isn't a too long time span.

Since debugging location features is hard (you need to leave your keyboard), it would be great if anyone could help me out with the testing. Here is a signed test APK for anyone interested.

- [trackbook-app-test-1.1.11-01.apk](https://www.dropbox.com/s/u8i2cjc29c13vic/trackbook-app-test-1.1.11-01.apk?dl=0)

**Comment by y20k** [comment]
Uups. I am doing a field test and the app crashes, when it has to deal with an imprecise location. I will fix that later this evening and I will provide a new APK. Tricky location debugging :-)

**Comment by y20k** [comment]
Okay. As promised a new APK for testing:

* [trackbook-app-test-1.1.11-02.apk](https://www.dropbox.com/s/m39911jiybjkln8/trackbook-app-test-1.1.11-02.apk?dl=0)

This one does not crash, when recording was started with an old location :-) Speaking of: Old location is now anything older than a minute.

**Comment by Hob111** [comment]
Hi,

I'm currently on a walking holiday so can't get onto Github. However, will install new version and give it a try.

R 
-- 
Sent from my Android phone using K-9 Mail.

On 5 September 2018 16:40:18 BST, y20k <notifications@github.com> wrote:
Okay. As promised a new APK for testing:

*
[trackbook-app-test-1.1.11-02.apk](https://www.dropbox.com/s/m39911jiybjkln8/trackbook-app-test-1.1.11-02.apk?dl=0)

This one does not crash, when recording was started with an old location
:-) Speaking of: Old location is now anything older than a minute.

**Comment by Hob111** [comment]
Unfortunately for some reason I was unable to install the new APK so couldn't test it last week. The installation starts as normal then I simply get the message "**X** App not installed." 

Any ideas? I install Trackbook from the F-Droid depository. Does this APK carry the correct signature for that?

**Comment by y20k** [comment]
I created the APK again. I probably did something wrong the last time. 
* [trackbook-app-test-1.1.11-03.apk](https://www.dropbox.com/s/w089qp1sd1smokp/trackbook-app-test-1.1.11-03.apk?dl=0)

PS. I uninstalled the old version, before I installed the test APK. If you want to do the same: Save your tracks (located in: `/Android/data/org.y20k.trackbook/files/tracks`) first :smile:.

**Comment by Hob111** [comment]
I got the same problem with the new APK so it was nothing you'd done wrong. However, following your suggestion I uninstalled the old version (after backing up my data  :thumbsup:) and the installation went smoothly - clearly you can't install from an APK over the top of one from a depository. I'm on a walking trip from the 21st of this month so I'll be as impatient as possible when starting the app :smile: to put it through its paces.

**Comment by Hob111** [comment]
I'm having a problem with Trackbook crashing. Briefly:
1) Trackbook started fine after I'd installed it (see last post).
2) I copied my saved tracks back to /Android/data/org.y20k.trackbook/files/tracks and Trackbook crashed when I started it.
3) I removed the tracks again and it started fine.
4) I put a random file into /Android/data/org.y20k.trackbook/files/tracks (actually a calendar .ics file) and Trackbook crashed when I started it.

So apparently the presence of ANY(?) file in the tracks directory seems to cause a crash.
Consequently Trackbook is unstable when tracking.

I've tried both test-1.1.11-02.apk and test-1.1.11-03.apk (just in case). Please let me know if you need any more information or if there's anything you'd like me to try.

**Comment by y20k** [comment]
☠️ 💣 

Something is wrong here. I apologize. I am not sure. I do not have an explanation right now. Maybe it is the fact that the APK was built with an beta version of the Android Studio IDE. I will investigate.

In the meantime you should probably stick to the latest F-Droid release. Sorry.

**Comment by y20k** [comment]
A very quick a observation. Trackbook crashes if you try to save a track with zero waypoints. That is a new case that could not happen before - but now Trackbook is pickier. If the fist few locations location fixes are not precise, there can be a case, where nothing has been recorded at the time of save.

**Comment by Hob111** [comment]
No need to apologize, I'm delighted to have such good software and am very happy to assist with development in any way I can. Your observation about tracks with zero way points might explain why I got crashes when saving short test tracks. After such a crash Trackbook wouldn't restart until I deleted the temporary file in the tracks directory, so I stuck with reporting that very obvious but very strange bug - one of the oddest I've ever come across.  :confused:
I'll take your advice whilst walking next week and stick to the latest F-Droid release but I'm happy to install the next test version once you've found some time to look at the problem.

**Comment by y20k** [comment]
Here we go again 😄 I fixed two bugs: 1. non-trackbook files cannot cause a crash anymore if they were placed in the "tracks"-directory 2. Trying to save a track with zero waypoints does not result in a crash anymore (the user gets an "alert dialog" in that case).

I compiled (and signed) an APK reflecting those bugfixes:

* [trackbook-app-test-1.1.11-04.apk](https://www.dropbox.com/s/4r4lh1qn6p842iq/trackbook-app-test-1.1.11-04.apk?dl=0)

**Comment by Hob111** [comment]
On my phone 1.1.11-04 still crashes when there are .trackbook files in the "tracks" directory. :-( 
(O/S Android Marshmallow 6.0.3)

**Comment by Hob111** [comment]
No, I only have tracks created using 1.1.10 (or earlier) and to test 1.1.11-04 I just put the last track I created on 7th September into the tracks directory. That was created by 1.1.10. In fact I've never managed to save a track using any version of 1.1.11 although I've not tried 04 having found the crash we're discussing.

I'm very pleased to help, I always enjoyed debugging although I wish I could offer more practical help.

**Comment by y20k** [comment]
> In fact I've never managed to save a track using any version of 1.1.11

Even with no tracks copied back from an older version? That is so strange. I have recorded several (10+) tracks using v1.1.11 - and I have copied back stuff. There must be a difference between the debug-version I am using and the release APK you are using. I need to check that.

**Comment by y20k** [comment]
Okay. The short story is: I think, I found the bug, fixed it and compiled a new APK.

* [trackbook-app-test-1.1.11-06.apk](https://www.dropbox.com/s/tgspgzcvgsdy374/trackbook-app-test-1.1.11-06.apk?dl=0)

The slightly longer one: the ProGuard extension (used during the compile process) compresses and optimizes APKs before release. Trackbook serializes and de-serializes track objects to storage (e.g. saves them). Somehow I guess Proguard alters the structure of objects in a way that is fine while running the app. But as soon as it gets to a de/serialize-operation the app needs the intended object structure, otherwise it crashes. I did some testing, actually installing the APK myself (since I now know it is not 100% identical to the debug APK I was using before) - and so far it worked for me.

Lets see how your experience is.

**Comment by Hob111** [comment]
One tiny but not critical bug. For some reason the white or red spot in the middle of the blue circle sometimes disappears. 
Run Trackbook, start, stop and clear a track (no need to wait for it to record any track points) then go to "Last Tracks" back to "Map" and start another track. 

I'll leave you to figure that one out while I have a good time walking in Devon :smiley:  :smirk:

**Comment by y20k** [comment]
This is a new bug. It deserves its own issue (#43). Thank you for finding a way to easily reproduce it!! I stumbled upon this problem, too, but I could pin point it.

**Comment by y20k** [comment]
There is a new APK over at issue #43 that hopefully fixes the recording icon bug.

**Comment by Hob111** [comment]
I've been unable to "persuade" v1.1.11-06 or v1.1.11-07 to use an out of date starting point so that bug seems to be fixed, but it's difficult to prove a negative so more testing is probably needed. 

However, the fix seems to have caused a new problem. I've been opening Trackbook and immediately tapping the "Start button" before turning off the screen and starting to walk. This seemed the best way to give it out of date GPS data to handle.

On 2 occasions (out of 9, other 7 OK) Trackbook has correctly logged the first two track points then stopped logging new points. On both occasions I've paused the walk a few km later and turned on the phone screen to pause the tracking. The notification on the locked screen said Trackbook was recording and it pauses OK, but there are only two track points on the plot. If the tracking is then resumed tracking proceeds as it should. I'll upload a track for you to look at.  I don't think this is a problem with GPS on my phone which seems to be working OK.
[2018-09-24-13-40-00.gpx.txt](https://github.com/y20k/trackbook/files/2442358/2018-09-24-13-40-00.gpx.txt)

A couple of other observations regarding these two tracks.
1. The walk distance given by Trackbook in the Statistics **does not** include the first two track points and has been calculated from the place the tracking was resumed. This is in contrast to the original bug where the (incorrect) start point was used in the distance calculation as it is for tracks that have recorded correctly.
2. The second track point is plotted in grey not blue - this seems to be a function of osmdroid and is probably trivial.

I hope this is clearly expressed. Please let me know if more information or clarification is needed.

**Comment by y20k** [comment]
> Trackbook has correctly logged the first two track points then stopped logging new points

Now that is really bad. I need to think about it. I had a lot of problems with Android variants that try to kill the app because of the battery consumption that logging location data causes. 

Additionally two out of nine walks is especially bad. Because it is way too often to be acceptable, while at the same time not often enough to be easily fixed.

**Comment by poet-man1** [comment]
I am still here, but to be honest, had not much possibility to follow this thread, due to personal health reasons.
I will read me through this thread at weekend, and see whether I understand, what this all is about.
If somebody want's to, a few short lines with the main contents would be appreciated.
After this I will ask any questions (if any) and activate trackbock and do some testing.
Ok?

**Comment by Hob111** [comment]
@poet-man1 Sorry to hear you've been unwell, I hope your health is improving. I'll try to summarise.

1. @poet-man reported a track with a very odd distance.
2. I had a similar problem, it seems Trackbook was using an out of date GPS location at the start of the Track.
3. @y20k produced a new apk. there have been several versions, ignore all but trackbook-app-test-1.1.11-07.apk which you'll find in issue #43.
4. This seems to have fixed the original bug but introduced another (see 5. below), although to eliminate the possibility that my phone is at fault and to provide more data my findings need to be confirmed.
5. I found that if tracking is started **immediately** Trackbook is loaded it sometimes records two track points and then stops recording until tracking is paused and resumed (see my **long** comment of two days ago for more detail).

To install v1.1.11-07 using the .apk you'll need to uninstall the stable version. Back up your old track data first or you'll lose it. :angry:. It's stored in /Android/data/org.y20k.trackbook/files/tracks 

Let me know if my English isn't clearly expressed - your English is a lot better than my German!

**Comment by poet-man** [comment]
Health has nearly recovered .... at least to the point it was before.
I understand what you summarise
Just one question for understanding details ....
In 2. you say Trackbook was using "an out of date" GPS location. What does it mean? When is a GPS location "out of date". And is it a location GPS recovers from Trackbook data or where does it come from?

Your English really is ok. So don't worry, not being understood.

**Comment by y20k** [comment]
@Hob111 and @poet-man 

This issue has a lot of comments and covers different problems. I think we should split it up. Would that be okay? My suggestion:

* Lets discuss here only the problem that Trackbook sometimes records a waypoints that are are off - resulting in crazy distances(@poet-man ) or incorrect starting points (@Hob111) 

* Lets put the new problems in separate / new issues

    1. Trackbook stops after two recorded waypoints (@Hob111 )

    2. Trackbook does not add up waypoints resulting in too short tracks (@Hob111 )

**Comment by poet-man** [comment]
Was not really involved in procedures so far, but think it would make sense to split up. Otherwise would move arround between different issues.
Publish current version: Only makes sense, if problems already existed in old version. I donot think it a good idea to publish a version with new problems.
My opinion.

**Comment by y20k** [comment]
> Publish current version: Only makes sense, if problems already existed in old version.

You are right. We should check if the new bugs were a result of the changes I made to the app.

**Comment by poet-man** [comment]
Yes .... I remember earlier times, when I was involved in software-testing. Users always where not too happy, when they got an update, solving problems, but presenting new problems.

**Comment by Hob111** [comment]
You guys have been busy! To take the issues you raise in reverse order (we English are always perverse :smiley:)

I agree it is unwise to publish a version which might contain new bugs even if it fixes existing ones. When I wrote software my inbox would be full of irate emails if I ever did such a thing. :innocent:

Before forking two new issues from this one, that is:

1. Trackbook stops after two recorded waypoints (@Hob111 )
2. Trackbook does not add up waypoints resulting in too short tracks (@Hob111 )

I'd be much happier if one of you manages to reproduce my new "bugs". I have a nagging fear that it may be my phone that is getting a bit flaky. The first "bug" seems to lead to the second one - I'm not sure why.

Finally, I agree that we should discuss here only the problem that Trackbook sometimes records waypoints that are are off - resulting in crazy distances(@poet-man ) or incorrect starting points (@Hob111). I have a hunch that v1.1.11-07 has fixed this but more testing is needed.

So may I suggest that we all continue to test to see if we can reproduce the original bug and if one of you finds "my new bugs" the issues are split as suggested by @y20k. If neither of you can reproduce them it looks like I need a new phone  :moneybag: :cry:

**Comment by poet-man** [comment]
So I have done some testing today concerning trackbook on my Galaxy tab/android 7, and .... no problems whatsoever!!!!!
What I have done:
1) Done tracking very normal
2) Done tracking, then stopped, started new tracking in about 100 m distance (in one case in about 2 km distance).
3) Started tracking immediately  after start-button was there
In all casses, trackbook started with current position. In case of immediate start after trackbook is loaded, I first could see the last position of last recording on screen, but after a few seconds it switched to current position.
Also changing means of transportation (ie walking to going by car) did not produce any problem (AFAIK).
In the time coming, I will use trackbook in every situation, that comes up. If there is any problem, I will report.
If there is a special situation, I should test, please feel free to describe.
Finally 2 points, that came up (no problem, only a situation, when I didnot know, what to do. Maybe somebody knows how to handle:
1) Tabbing on 'Statistics' right at the bottom, the screen moves up, but when I tab somewhere in that 'window', it wont go down again. I will have to repeat tabbing several times, to get it closed.
2) When GPS is off (which most times is, to save battery), trackbook tells me at the bottom, that GPS is off and trackbook wont work. This messege constantly is there, so that I cannot reach last recordings, which is hidden behind that message. I will have to turn on GPS, to get there.

**Comment by Hob111** [comment]
Oh dear, :iphone: :hammer:

Tap the _i_, top right of statistics screen.

I've not seen the other message because my GPS is always on (supposedly 😑 )

**Comment by poet-man** [comment]
Yes, that's what I did with that screen, not going down.
And GPS I have to turn off, otherwise my battery would go down rather soon. My tablet is fantastic. The only thing is, that battery capacity was designed a little bit too small.

**Comment by Hob111** [comment]
That's odd. I've just tried both methods on my tablet (Lenovo Yoga Tab 3) and they both work as they do on my phone.

I understand about GPS, the battery on this tablet is huge so not an issue, and my phone battery lasts a couple of days with GPS on. I do, however, lock down the Google apps which normally use GPS data, so my GPS, although turned on, isn't running much of the time. 
-- 
Sent from my Yoga Tab using K-9 Mail.

**Comment by poet-man** [comment]
So maybe its a 'feature' on my galaxy tablet. Not seen anywhere else on it, so far, but who knows. I will test on trackbook … maybe I had a nervous finger yesterday 😊

**Comment by poet-man** [comment]
Being on my way into town today, I seem to have had an issue (no opportunity to reproduce so far):
Was in a building with obviously no GPS signal there. Just about to leave there, I activated GPS and started trackbook. Of course trackbook told, that there is no GPS and it wont work. Ok, I thought .... left building, so GPS should be available outside. But tabbing on starting to record, trackbook still told me, there was no GPS. So turned off GPS, turned it on again .... no change. So closed trackbook, started it again .... everything ok and I could start recording.
I would have expected, that recording would have been possible, as soon as GPS signal was available.
Can anybody reproduce?

**Comment by Hob111** [comment]
I can't think of a building near me that is large enough to block the GPS signal and I live in a bungalow, so I tried the following.

Switched off GPS and started Trackbook.
Got the message that Location is turned off etc. and the default map of Heidelberg University.
Turned on GPS, tapped start and after a delay got the current location map and tracking started.

Not precisely the same as your situation but the best I can do at the moment. Let me know if you think there is anything else I can try.

**Comment by poet-man** [comment]
First I will try to reproduce this. Just one ocassion, when it happend, surely is not often enough.
Here where I live, lack of GPS is not difficult to reach. My hometown is in a sort of valley, so that a weak GPS signal turns into no signal, when being in a building.
I will try to reproduce, going downstairs to cellar, where their also might be no signal

**Comment by poet-man** [comment]
Hi there. Reproduced it today. That 'problem' I have with no GPS signal, when starting trackbook. Dont know whether others can reproduce this too.
So, this is how it happens:
1. GPS on my tablet is off (normal situation with me).
2. Go to basement/cellar in the building where I live (no GPS signal available down there).
3. Turn on GPS. Turn on Trackbook. Trackbook, of course, says: No GPS.
4. Head off to town. Tabbing on 'start recording' in Trackbook still says 'no GPS.
5. Restart of GPS: No change.
6. Restart of Trackbook: Now recording will work.
No probs whatsoever in any other circumstances. Also no probs, when GPS signal gets lost during recording (ie having break in a building)
Regards
Axel

**Comment by y20k** [comment]
Hi there, sorry for the late answer. I just went down to the basement of the house I am living in. Location off and Airplane mode off. I was not able to reproduce the problem. That does not mean that this is not a bug. Perhaps we should move over the discussion to a separate issue, so that the problem does not get lost in this rather long thread. Anyway. Heads up for finding this strange problem - especially for going bug hunting in your basement. That may sound snarky too you, but I am totally honest. Good job. 👍

**Comment by Hob111** [comment]
I've not been able to check this because I have nowhere without a GPS signal, you must have a lot of cellars in Germany :smile:.

1. I agree this should be moved to a separate issue. 
2. The original bug of this thread and issue #4, which seems to be another manifestation of the same problem, both seem to be fixed by v1.1.11-07. 
3.  No one else has been able to reproduce my bug, "Trackbook stops after two recorded way points" and I have reason to believe it may be a problem with my phone.

Therefore I suggest:

1. v1.1.11-07 should be published.
2. Issues #4 and #21 should be closed.
3. A new issue should be opened for "No GPS signal when starting Trackbook", (I'm sure that could be worded better!). 

What do you both think?

**Comment by poet-man** [comment]
That sounds reasonable.
I will go on finding other situations with no GPS 😉

**Comment by y20k** [comment]
Okay since we all agree, I will close this issue. I published the accuracy fix today, Thanks for the great discussions here!!
